#!/usr/bin/env python3

import sys
import time


def confirm():
    while True:
        try:
            from fsm_hub import core
            break
        except Exception as e:
            print(e, file=sys.stderr, flush=True)
            time.sleep(1)


if __name__ == '__main__':
    confirm()
    from fsm_hub.app import main
    main()
